language: generic
sudo: required
services:
  - docker


after_success:
  - docker build -t kllx/multi-client ./client
  - docker build -t kllx/multi-nginx ./nginx
  - docker build -t kllx/multi-server ./server
  - docker build -t kllx/multi-worker ./worker

  - echo "$DOCKER_PASSWORK" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kllx/multi-client
  - docker push kllx/multi-nginx
  - docker push kllx/multi-server
  - docker push kllx/multi-worker
